## 문제 1. 
문제: 모든 값이 0으로 2차원 배열 (5, 5) 만드세요. 

In [17]:
import numpy as np
np.zeros((5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
np.zeros(25).reshape(5, 5)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## 문제 2. 
임의의 3x3 크기의 배열을 생성하고 배열의 shape(모양), dtype(데이터 타입), 그리고 배열의 차원 수(ndim)를 출력하세요.

In [19]:
arr = np.zeros((3, 3))
arr.shape, arr.dtype, arr.ndim

((3, 3), dtype('float64'), 2)

## 문제 3. 
- 주어진 배열에서 아래와 같이 슬라이싱 하세요. 
```
array([[ 5,  6],
       [ 9, 10]])
```

In [27]:
arr = np.arange(16).reshape(4, 4)
arr[1:3, 1:3]

array([[ 5,  6],
       [ 9, 10]])

## 조건 연산
- 원하는 결괏값 : True/False

In [29]:
arr = np.array([10, 20, 30])
arr > 10

array([False,  True,  True])

In [30]:
arr = np.array([10, 20, 30])
cond = [False, True, True]

arr[cond]

array([20, 30])

In [31]:
arr = np.array([18, 20, 50, 30, 16])
cond = arr > 18

arr[cond]

array([20, 50, 30])

In [32]:
arr = np.array([18, 20, 50, 30, 16])
arr[arr > 18]

array([20, 50, 30])

In [36]:
arr = np.array([18, 20, 50, 30, 16, 65, 70])
cond0 = arr > 18
cond1 = arr < 65

arr[cond0 & cond1]

array([18, 20, 50, 30, 16])

In [37]:
arr[cond0 | cond1]

array([18, 20, 50, 30, 16, 65, 70])

In [38]:
# 권장사항, 이유 : pandas 다중조건 필터링할 때는 아래 방법으로만 가능
# () 반드시 필요 
arr[(cond0 | cond1)]

array([18, 20, 50, 30, 16, 65, 70])

## np.where 
- 

In [39]:
import numpy as np
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
np.where(a < 5, a, 10*a)

array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

# 함수와 메서드

In [51]:
arr = np.arange(8).reshape(2, 4)
arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [52]:
arr.sum(axis = None)

np.int64(28)

In [53]:
arr.sum(axis = 0) # x축 방향으로 데이터의 합을 구하라, 행 단위

array([ 4,  6,  8, 10])

In [54]:
arr.sum(axis = 1) # y축 방향으로 열 단위로 데이터의 합을 구하라

array([ 6, 22])

In [150]:
# 무작위 랜덤 함수 사용
np.random.seed(42) # 머신러닝 할 때, 이 코드를 자주 사용
np.random.randint(10)

6

In [153]:
np.random.randint(46, size=6) # 46 의미하는 것은 0~45번째까지의 숫자중 무작위로 가져오겠음 

array([35, 39, 23,  2, 21,  1], dtype=int32)

In [175]:
np.random.randint(46, size=(3, 4))

array([[ 2, 19, 23, 32],
       [23, 10,  7, 35],
       [37, 39, 19, 34]], dtype=int32)

In [181]:
x = np.linspace(0, 100, 11)
print(x)

[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


# Pandas Series 

In [183]:
import pandas as pd 
pd.__version__

'2.2.3'

In [184]:
data = [10, 20, 30]
s = pd.Series(data)
s

0    10
1    20
2    30
dtype: int64

In [185]:
print(type(s))

<class 'pandas.core.series.Series'>


In [186]:
import numpy as np 

data = np.arange(5)
s = pd.Series(data)
s

0    0
1    1
2    2
3    3
4    4
dtype: int64

In [187]:
import numpy as np 

data = np.arange(5)
s = pd.DataFrame(data)
s

0
0  0
1  1
2  2
3  3
4  4

In [189]:
data = ["시가", "고가"]
s = pd.Series(data)
s

0    시가
1    고가
dtype: object

In [190]:
data = [80000, "90000"]
s = pd.Series(data)
s

0    80000
1    90000
dtype: object

## 시리즈 인덱스

In [194]:
data = [1000, 2000, 3000]
s = pd.Series(data)
print(s.index, type(s.index))

RangeIndex(start=0, stop=3, step=1) <class 'pandas.core.indexes.range.RangeIndex'>


In [195]:
list(s.index)

[0, 1, 2]

In [196]:
s.index.to_list()

[0, 1, 2]

In [198]:
# help(s.index) # 클래스에는 항상 속성과 메서드가 존재한다. 

In [229]:
# 시리즈 생성하면서 인덱스도 같이 생성
data = [1000, 2000, 3000]
index = ["메로나", "월드콘", "와"]

s = pd.Series(data=data, index=index)
s.index

Index(['메로나', '월드콘', '와'], dtype='object')

In [221]:
s.values, type(s.values)

(array([1000, 2000, 3000]), numpy.ndarray)

In [228]:
s

메로나    1000
월드콘    2000
와      3000
dtype: int64

## 시리즈 인덱싱

In [222]:
print(s.iloc[0])

1000


In [226]:
print(s.loc['메로나'])

1000


In [231]:
# 시리즈 생성하면서 인덱스도 같이 생성
data = [1000, 2000, 3000]
# index가 없음

s2 = pd.Series(data=data)
s2.index.to_list()

[0, 1, 2]

In [233]:
print(s2.iloc[0]) # iloc에서의 0은 위치 0을 의미
print(s2.loc[0]) # loc에서의 0은 라벨 0을 의미

1000
1000


## 슬라이싱

In [237]:
s.iloc[0:2]

메로나    1000
월드콘    2000
dtype: int64

In [239]:
s.loc["메로나":"와"]

메로나    1000
월드콘    2000
와      3000
dtype: int64

In [241]:
s2.iloc[0:2]

0    1000
1    2000
dtype: int64

In [242]:
s2.loc[0:2]

0    1000
1    2000
2    3000
dtype: int64

## 시리즈 수정/추가/삭제

In [248]:
data = [1000, 2000, 3000]
index = ["메로나", "월드콘", "와"]

s = pd.Series(data=data, index=index)
s

메로나    1000
월드콘    2000
와      3000
dtype: int64

In [249]:
s['메로나'] = 500
s

메로나     500
월드콘    2000
와      3000
dtype: int64

In [247]:
s.iloc[0] = 500
s

메로나     500
월드콘    2000
와      3000
dtype: int64

In [245]:
s.loc['메로나'] = 500
s

메로나     500
월드콘    2000
와      3000
dtype: int64

# 시리즈 연산

In [256]:
import pandas as pd 

evan = pd.Series([10, 20, 300], index=['NAVER', 'APPLE', '엔비디아'])
딸1 = pd.Series([10, 30, 20], index=["엔비디아", "NAVER", "APPLE"])

evan

NAVER     10
APPLE     20
엔비디아     300
dtype: int64

In [257]:
딸1

엔비디아     10
NAVER    30
APPLE    20
dtype: int64

In [258]:
evan + 딸1

APPLE     40
NAVER     40
엔비디아     310
dtype: int64

In [259]:
evan = pd.Series([10, 20, 300], index=['NAVER', 'APPLE', '테슬라'])
딸1 = pd.Series([10, 30, 20], index=["엔비디아", "NAVER", "APPLE"])

evan + 딸1

APPLE    40.0
NAVER    40.0
엔비디아      NaN
테슬라       NaN
dtype: float64

In [262]:
date = ["6/1", "6/2", "6/3", "6/4", "6/5"]
high = pd.Series([42800, 42700, 42050, 42950, 43000], index=date) # 매도
low = pd.Series([42150, 42150, 41300, 42150, 42350] , index=date) # 매수

diff = high - low
print(diff)

6/1    650
6/2    550
6/3    750
6/4    800
6/5    650
dtype: int64


In [267]:
diff.idxmax(), diff[diff.idxmax()]

('6/4', np.int64(800))

In [268]:
diff.idxmin(), diff[diff.idxmin()]

('6/2', np.int64(550))

In [269]:
profit = high / low # 단순 수익률 계산
profit

6/1    1.015421
6/2    1.013049
6/3    1.018160
6/4    1.018980
6/5    1.015348
dtype: float64

In [270]:
profit.cumprod()

6/1    1.015421
6/2    1.028671
6/3    1.047351
6/4    1.067230
6/5    1.083610
dtype: float64

# 시리즈와 Map

In [279]:
text = '1,234'
result = int(text.replace(',',''))
type(result), result

(int, 1234)

In [280]:
num_str = ['1,234', '5,678', '12,345']
results = []
for num in num_str:
    temp = int(num.replace(',',''))
    results.append(temp)

results

[1234, 5678, 12345]

In [283]:
def rm_comma(x):
    return int(x.replace(',',''))

In [284]:
def rm_comma(x):
    return int(x.replace(',',''))
s = pd.Series(['1,234', '5,678', '12,345'])
result = s.map(rm_comma)
result

0     1234
1     5678
2    12345
dtype: int64

In [285]:
def remove_dollar_sign(x):
    return float(x.replace('$', '').replace(',', ''))
s = pd.Series(['$1,234.56', '$5,678.90', '$12,345.67'])
result = s.map(remove_dollar_sign)
result

0     1234.56
1     5678.90
2    12345.67
dtype: float64

## 문제
- 기준점이 13이상
  + 크다 or 작다

In [289]:
def is_greater_13(x): 

    return_text = None
    if x >= 13:
        return "크다"
    else:
        return "작다" 

s = pd.Series([10, 15, 7, 20, 13])
s.map(is_greater_13)

0    작다
1    크다
2    작다
3    크다
4    크다
dtype: object

In [291]:
result = s.map(lambda x: '크다' if x >= 13 else '작다')
print(result)

0    작다
1    크다
2    작다
3    크다
4    크다
dtype: object


In [292]:
result = s.apply(lambda x: '크다' if x >= 13 else '작다')
print(result)

0    작다
1    크다
2    작다
3    크다
4    크다
dtype: object


## 필터링

In [294]:
data = [42500, 42550, 41800, 42550, 42650]
index = ['2019-05-31', '2019-05-30', '2019-05-29', '2019-05-28', '2019-05-27']
s = pd.Series(data=data, index=index)
s

2019-05-31    42500
2019-05-30    42550
2019-05-29    41800
2019-05-28    42550
2019-05-27    42650
dtype: int64

In [295]:
cond = s > 42000
print(cond)

2019-05-31     True
2019-05-30     True
2019-05-29    False
2019-05-28     True
2019-05-27     True
dtype: bool


In [296]:
s[cond]

2019-05-31    42500
2019-05-30    42550
2019-05-28    42550
2019-05-27    42650
dtype: int64

In [297]:
s[s > 42000]

2019-05-31    42500
2019-05-30    42550
2019-05-28    42550
2019-05-27    42650
dtype: int64

In [304]:
from pandas import Series
# import pandas as pd
# pd.Series()

close = [42500, 42550, 41800, 42550, 42650]
open = [42600, 42200, 41850, 42550, 42500]
index = ['2019-05-31', '2019-05-30', '2019-05-29', '2019-05-28', '2019-05-27']

open = Series(data=open, index=index)
close = Series(data=close, index=index)

# 문제: 종가가 시가보다 높은 날을 구하세요
# close > open
close[close > open]

2019-05-30    42550
2019-05-27    42650
dtype: int64