## 문제 1. 
문제: 모든 값이 0으로 2차원 배열 (5, 5) 만드세요. 

In [8]:
import numpy as np
arr = np.zeros((5,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## 문제 2. 
임의의 3x3 크기의 배열을 생성하고 배열의 shape(모양), dtype(데이터 타입), 그리고 배열의 차원 수(ndim)를 출력하세요.

In [10]:
arr = np.zeros((3,3))
arr.shape, arr.dtype, arr.ndim

((3, 3), dtype('float64'), 2)

## 문제 3. 
- 주어진 배열에서 아래와 같이 슬라이싱 하세요. 
```
array([[ 5,  6],
       [ 9, 10]])
```

In [12]:
arr = np.arange(16).reshape(4, 4)
arr[1:3, 1:3]

array([[ 5,  6],
       [ 9, 10]])