## 라이브러리 설치

In [ ]:
!pip install numpy  -> 추가로 라이브러리 설치 / 경로 확인 잘 할 것 

In [2]:
import numpy as np  #설치했다고 바로 쓸 수 있는 것이 아니라 import 해야함. 

print(np.__version__)

2.1.1


In [3]:
 # help(np)

In [4]:
num1 = [1, 2, 3]
num2 = [4, 5, 6]

In [5]:
num1_arr = np.array(num1)
num2_arr = np.array(num2)

num1_arr + num2_arr

array([5, 7, 9])

In [7]:
print(type(num1_arr))

<class 'numpy.ndarray'>


In [8]:
num1_arr.data

In [9]:
num1_arr.dtype -> 행렬의 

dtype('int64')

In [10]:
num1_arr.shape

(3,)

In [11]:
num1_arr.ndim

1

In [13]:
num1_arr.max()

np.int64(3)

# 우리 회사에서 주로 다루는 데이터는 0~100만원 미만

In [14]:
num1_arr = np.array(num1, dtype="int8")
num1_arr.dtype

dtype('int8')

## 배열 만드는 방법

In [16]:
# 기본적으로 다른 데이터 자료형으로 numpy배열로 변환
# 배열 생성

print(np.ones(3))

[1. 1. 1.]


In [17]:
print(np.zeros(3))   =>0을 출력하는 함수

[0. 0. 0.]


In [18]:
print(np.ndarray(shape=(2,2), dtype=float, order='F'))

[[0.00000000e+000 9.98679157e-312]
 [9.98679159e-312 9.98679158e-312]]


In [19]:
arr = np.ndarray(shape=(2,2), dtype=float, order='F')
arr.shape

(2, 2)

# 배열의 차원 변경

In [25]:
temp_arr = np.arange(16)
temp_arr.reshape(2, 2, 4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [29]:
a16 = np.array([1.333333],dtype = np.float16)
a32 = np.array([1.333333],dtype = np.float32)

print(a16)
print(a32)

print(a16/3)
print(a32/3)

[1.333]
[1.333333]
[0.4443]
[0.44444433]


In [30]:
arr = np.array([-1, 2, -3])
arr/0

C:\Users\campus3S020\AppData\Local\Temp\ipykernel_10944\3465403327.py:2: RuntimeWarning: divide by zero encountered in divide
  arr/0


array([-inf,  inf, -inf])

# 결측치
- Missing values : 잃어버린 값
- nan : Not a Number, ==> 아직 정의되지 않은 숫자 의미

In [31]:
print(np.nan, type(np.nan))

nan <class 'float'>


In [32]:
print(np.inf, type(np.inf))   #inf = 무한대

inf <class 'float'>


In [33]:
print(-np.inf, type(-np.inf))

-inf <class 'float'>


In [34]:
arr = np.array([-1, 2, -3])
print(arr + np.nan)
print(arr + np.inf)

[nan nan nan]
[inf inf inf]


## 인덱싱 & 슬라이싱

In [12]:
arr = np.arange(10)
arr[1:5]

array([1, 2, 3, 4])

In [13]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr = np.arange(10).reshape(2,5)
arr[0][1]

np.int64(1)

In [10]:
arr = np.arange(10000).reshape(100,100)
arr[0:4][0:1]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
        64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
        80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [16]:
arr = np.arange(4)
arr[1]

np.int64(1)

In [47]:
arr = np.arange(20).reshape(4,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [52]:
arr = np.arange(20).reshape(4,5)
arr[1:, 2:]   # => [행, 열]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

## 브로드캐스팅 연산

In [53]:
a = np.array([1,2,3])
b = np.array([1,2,3])
a + b

array([2, 4, 6])

In [54]:
a = np.array([1,2,3])
b = 3.0
a + b

array([4., 5., 6.])

## 조건 연산
- 원하는 결과값 : True/False

In [55]:
arr = np.array([10,20,30])
arr > 10

array([False,  True,  True])

In [56]:
arr = np.array([10,20,30])
cond = [False, True, True]

arr[cond]   # cond => True 값만 가져온다 (=>필터)

array([20, 30])

In [58]:
arr = np.array([18,20,50,30,16])
cond = arr > 18

arr[cond]

array([20, 50, 30])

In [59]:
arr = np.array([18,20,50,30,16])
arr[arr > 18]

array([20, 50, 30])

In [60]:
arr = np.array([18,20,50,30,16,65,70])
cond0 = arr > 18
cond1 = arr < 65

arr[cond0 & cond1]

array([20, 50, 30])

In [61]:
arr[cond0 | cond1]

array([18, 20, 50, 30, 16, 65, 70])

In [62]:
# 권장사항, 이유 : pandas 다중조건 필터링할 때는 아래 방법으로만 가능]
# () 반드시 필요 
arr[(cond0) | (cond1)]

array([18, 20, 50, 30, 16, 65, 70])

## np.where
- 

In [64]:
import numpy as np
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
np.where(a<5,a,10*a)

array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

# 함수와 메서드

In [66]:
arr = np.arange(8).reshape(4,2)
arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [67]:
arr.sum()

np.int64(28)

In [68]:
arr.sum(axis =0) #x축 방향으로 데이터의 합을 구하라 => 행 단위 

array([12, 16])

In [70]:
arr.sum(axis =1) #y축 방향으로 데이터의 합을 구하라 => 열 단위 

array([ 1,  5,  9, 13])

In [109]:
#무작위 랜덤 함수 만들기
np.random.seed(42)   #머신러닝 할 때, 이 코드를 자주 이용
np.random.randint(10)

6

In [108]:
np.random.randint(46, size=6)  # 46 의미하는 것은 0~45번째까지의 숫자중 무작위로 가져오겠음

array([18, 22, 10, 10, 23, 35], dtype=int32)

In [110]:
np.random.randint(46, size=(3,4))

array([[28, 14, 42,  7],
       [20, 38, 18, 22],
       [10, 10, 23, 35]], dtype=int32)

In [113]:
x = np.linspace(0, 100, 11)
print(x)

[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
